name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
            with:
              repository: cu-ecen-aeld/assignments-3-and-later-Sriram-Y
              token: ${{ secrets.GITHUB_TOKEN }}
              fetch-depth: 1 
          - name: Checkout submodules
            run: git submodule update --init --recursive
            env:
              GIT_TERMINAL_PROMPT: 0

          - name: Run unit test
            run: ./unit-test.sh

    full-test:
        container: cuaesd/aesd-autotest:24-assignment6
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
            with:
              repository: cu-ecen-aeld/assignments-3-and-later-Sriram-Y
              token: ${{ secrets.GITHUB_TOKEN }}
              fetch-depth: 1
          - name: Checkout submodules
            run: git submodule update --init --recursive
            env:
              GIT_TERMINAL_PROMPT: 0

          - name: Run full test
            run: ./full-test.sh
